"""End-to-end demonstration: synthetic spectra in, pressure and temperature out.

Run ``python demo.py``. A pressure and temperature scenario drives a
synthetic Fabry-Perot + FBG fibre, the demodulator recovers both
quantities from the spectra alone, and the figure (``demo.png``) compares
truth against recovery. Everything is generated by this repository's own
code; no measured data is involved.
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from fbgfp import fit, peaks, physics, synth, track

OPD_NM = 87_000.0  # cavity optical path difference: fringe period ~28 nm
BAND = (0.030, 0.042)  # pass band in cycles/nm, brackets the fringe frequency
REFERENCE_NM = 1560.0  # initial tracking reference
FBG_CENTERS_NM = [1525.4, 1540.6, 1554.8]  # internal FBG first, two static
N_FRAMES = 60


def scenario():
    """A charge-like transient: pressure builds and holds, heat comes and goes."""
    frames = np.arange(N_FRAMES)
    pressure_bar = 1.5 * (1.0 - np.exp(-frames / 15.0))
    temperature_c = 2.0 * np.sin(np.pi * frames / N_FRAMES)
    return pressure_bar, temperature_c


def main():
    pressure_true, temperature_true = scenario()

    # The sensitivities map the scenario onto spectral trajectories...
    delta_fpi = (
        physics.FPI_PRESSURE_NM_PER_BAR * pressure_true
        + physics.FPI_TEMPERATURE_NM_PER_C * temperature_true
    )
    delta_fbg = physics.FBG_TEMPERATURE_NM_PER_C * temperature_true

    # ...which the generator turns into spectra with noise and drift.
    wl = synth.wavelength_axis()
    # The tracked crest: the fringe maximum of order 55 (87000/55 = 1581.8 nm),
    # the one nearest the tracking reference. Converts wavelength shift to OPD.
    crest0 = OPD_NM / np.rint(OPD_NM / 1581.8)
    centers = np.tile(FBG_CENTERS_NM, (N_FRAMES, 1))
    centers[:, 0] += delta_fbg
    seq = synth.simulate_sequence(
        wl,
        opd_nm=OPD_NM * (1.0 + delta_fpi / crest0),
        fbg_centers_nm=centers,
        noise_db=0.2,
        drift_amplitude_db=0.3,
        seed=0,
    )

    # Demodulation: track the fringe crest and the internal FBG, then
    # separate pressure from temperature with the calibration matrix.
    fp = track.track_fp(seq.spectra_db, wl, BAND, REFERENCE_NM)
    fbg = track.track_fbg(seq.spectra_db, wl, [FBG_CENTERS_NM[0]])
    pressure, temperature = physics.separate_pressure_temperature(
        fbg[:, 0] - fbg[0, 0], fp.corrected_nm - fp.corrected_nm[0]
    )

    # One frame demodulated step by step, for the method panels.
    step_nm = wl[1] - wl[0]
    filtered = peaks.fft_bandpass(peaks.linearize(seq.spectra_db[0]), step_nm, BAND)
    valleys = peaks.find_valleys(wl, filtered)
    left, right = peaks.nearest_valley_pair(valleys, REFERENCE_NM)
    crest = fit.fit_fringe_crest(wl, filtered, left, right)

    fig, axes = plt.subplots(2, 2, figsize=(13, 8), constrained_layout=True)

    axes[0, 0].plot(wl, seq.spectra_db[0], lw=0.4)
    axes[0, 0].set_title("Synthetic multiplexed spectrum: FP fringe + 3 FBG peaks")
    axes[0, 0].set_xlabel("Wavelength (nm)")
    axes[0, 0].set_ylabel("Power (dB)")

    axes[0, 1].plot(wl, filtered, lw=0.5, label="band-passed fringe")
    valley_idx = np.searchsorted(wl, valleys)
    axes[0, 1].plot(valleys, filtered[valley_idx], "v", ms=5, label="valleys")
    window = (wl >= left) & (wl <= right)
    axes[0, 1].plot(
        wl[window],
        fit.gaussian(wl[window], crest.amplitude, crest.center, crest.sigma, crest.offset),
        "--",
        lw=1.5,
        label=f"Gaussian crest fit: {crest.center:.3f} nm",
    )
    axes[0, 1].set_title("FFT band-pass + valley detection + crest fit")
    axes[0, 1].set_xlabel("Wavelength (nm)")
    axes[0, 1].set_ylabel("Filtered amplitude")
    axes[0, 1].legend(loc="lower left", fontsize=8)

    axes[1, 0].plot(pressure_true, "-", label="true")
    axes[1, 0].plot(pressure, ".", ms=4, label="recovered from spectra")
    axes[1, 0].set_title("Pressure: truth vs demodulated")
    axes[1, 0].set_xlabel("Frame")
    axes[1, 0].set_ylabel("Pressure change (bar)")
    axes[1, 0].legend()
    axes[1, 0].annotate(
        "wobble = baseline drift leaking into the pass band\n"
        "(characterized and bounded in the tests)",
        xy=(0.98, 0.05), xycoords="axes fraction", ha="right", fontsize=8,
        color="0.35",
    )

    axes[1, 1].plot(temperature_true, "-", label="true")
    axes[1, 1].plot(temperature, ".", ms=4, label="recovered from spectra")
    axes[1, 1].set_title("Temperature: truth vs demodulated")
    axes[1, 1].set_xlabel("Frame")
    axes[1, 1].set_ylabel("Temperature change (°C)")
    axes[1, 1].legend()
    axes[1, 1].annotate(
        "scatter = FBG fit jitter (~5 pm) over the\n"
        "10.2 pm/°C sensitivity — the resolution floor",
        xy=(0.98, 0.05), xycoords="axes fraction", ha="right", fontsize=8,
        color="0.35",
    )

    fig.savefig("demo.png", dpi=150)
    print("Wrote demo.png")
    rms_p = np.sqrt(np.mean((pressure - pressure_true) ** 2))
    rms_t = np.sqrt(np.mean((temperature - temperature_true) ** 2))
    print(f"Pressure recovered to {rms_p:.3f} bar RMS "
          f"(range {pressure_true.max():.1f} bar) over {N_FRAMES} frames")
    print(f"Temperature recovered to {rms_t:.2f} °C RMS "
          f"(range {temperature_true.max():.1f} °C)")
    return rms_p, rms_t


if __name__ == "__main__":
    main()
