"""Pipeline viewer for the fbg-fp-demod method.

The page shows the demodulation the way the original MATLAB displayed it,
one spectrum at a time: the raw spectrum, its FFT with the pass band
marked, the band-filtered fringe with the Gaussian crest fit, and the
resulting FPI trajectory underneath. A frame slider steps through the
sequence.

Two data sources: a synthetic scenario generated by ``fbgfp.synth`` (works
anywhere), or a local ENLIGHT ``Responses*.txt`` export read with
``fbgfp.io`` — the file is read on this machine and nothing leaves it.

Run with ``streamlit run app/main.py`` (requires ``pip install .[app]``).
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import streamlit as st

from fbgfp import fit, io, peaks, physics, synth, track

SYNTH_REFERENCE_NM = 1540.0
INTERNAL_FBG_NM = 1525.4
STATIC_FBG_NM = 1554.8


def derived_band(opd_nm, wavelength_nm):
    """Pass band bracketing the fringe frequency f = OPD / wl^2."""
    f_max = opd_nm / wavelength_nm[0] ** 2
    f_min = opd_nm / wavelength_nm[-1] ** 2
    return 0.85 * f_min, 1.15 * f_max


@st.cache_data(max_entries=16)
def synthetic_sequence(p_max, t_max, n_frames, noise_db, drift_db, opd_nm):
    """A charge-like scenario mapped onto spectra through the calibration."""
    frames = np.arange(n_frames)
    pressure = p_max * (1.0 - np.exp(-frames / 15.0))
    temperature = t_max * np.sin(np.pi * frames / n_frames)
    delta_fpi = (
        physics.FPI_PRESSURE_NM_PER_BAR * pressure
        + physics.FPI_TEMPERATURE_NM_PER_C * temperature
    )
    crest0 = opd_nm / np.rint(opd_nm / SYNTH_REFERENCE_NM - 0.5)
    centers = np.column_stack(
        [
            INTERNAL_FBG_NM + physics.FBG_TEMPERATURE_NM_PER_C * temperature,
            np.full(n_frames, STATIC_FBG_NM),
        ]
    )
    wl = synth.wavelength_axis()
    seq = synth.simulate_sequence(
        wl,
        opd_nm=opd_nm * (1.0 + delta_fpi / crest0),
        fbg_centers_nm=centers,
        noise_db=noise_db,
        drift_amplitude_db=drift_db,
        seed=0,
    )
    return wl, seq.spectra_db, None  # no timestamps for synthetic frames


@st.cache_data(max_entries=4)
def load_export(path, channel, max_spectra):
    loaded = io.read_responses(path, channel=channel, max_spectra=max_spectra)
    hours = [
        (t - loaded.timestamps[0]).total_seconds() / 3600.0
        for t in loaded.timestamps
    ]
    return loaded.wavelength_nm, loaded.spectra_db, np.array(hours)


@st.cache_data(max_entries=16)
def run_tracker(wavelength_nm, spectra_db, band, reference_nm, trim):
    result = track.track_fp(spectra_db, wavelength_nm, band, reference_nm, trim=trim)
    return result.corrected_nm, result.valley_nm, result.hop_frames


def pipeline_figure(wl, spectrum_db, band, tracked_valley_nm, trim):
    """One frame through the method: raw, FFT, filtered fringe with fit."""
    step_nm = wl[1] - wl[0]
    linear = peaks.linearize(spectrum_db)
    filtered = peaks.fft_bandpass(linear, step_nm, band)
    valleys = peaks.find_valleys(wl, filtered)
    left, right = peaks.nearest_valley_pair(valleys, tracked_valley_nm)
    crest = fit.fit_fringe_crest(wl, filtered, left, right, trim=trim)

    fig, axes = plt.subplots(3, 1, figsize=(11, 9), constrained_layout=True)

    axes[0].plot(wl, spectrum_db, lw=0.4)
    axes[0].set_title("1 - Raw spectrum")
    axes[0].set_xlabel("Wavelength (nm)")
    axes[0].set_ylabel("Power (dB)")

    freqs = np.fft.rfftfreq(linear.size, d=step_nm)
    amplitude = np.abs(np.fft.rfft(linear - linear.mean()))
    amplitude /= amplitude.max()
    show = freqs <= max(3.0 * band[1], 0.1)
    axes[1].plot(freqs[show], amplitude[show], lw=0.8)
    axes[1].axvspan(band[0], band[1], color="tab:orange", alpha=0.25,
                    label=f"pass band {band[0]:.4f}-{band[1]:.4f}")
    axes[1].set_title("2 - FFT of the linearized spectrum (spatial frequency)")
    axes[1].set_xlabel("Frequency (cycles/nm)")
    axes[1].set_ylabel("Normalized amplitude")
    axes[1].legend(fontsize=8)

    axes[2].plot(wl, filtered, lw=0.5, label="band-passed fringe")
    valley_idx = np.searchsorted(wl, valleys)
    axes[2].plot(valleys, filtered[valley_idx], "v", ms=5, label="valleys")
    window = (wl >= left) & (wl <= right)
    axes[2].plot(
        wl[window],
        fit.gaussian(wl[window], crest.amplitude, crest.center, crest.sigma, crest.offset),
        "--", lw=1.5,
        label=f"Gaussian crest fit: {crest.center:.4f} nm",
    )
    axes[2].axvline(crest.center, color="k", lw=0.8, ls=":")
    axes[2].set_title("3 - Filtered fringe, valleys, and the demodulated reading")
    axes[2].set_xlabel("Wavelength (nm)")
    axes[2].set_ylabel("Filtered amplitude")
    axes[2].legend(loc="lower left", fontsize=8)
    return fig


def trajectory_figure(x, shift_pm, frame, xlabel):
    fig, ax = plt.subplots(figsize=(11, 3), constrained_layout=True)
    ax.plot(x, shift_pm, lw=0.7)
    ax.plot(x[frame], shift_pm[frame], "o", ms=8, mfc="none", mec="tab:red",
            label=f"current frame ({shift_pm[frame]:+.1f} pm)")
    ax.set_title("4 - Demodulated FPI trajectory")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("FPI shift (pm)")
    ax.legend(fontsize=8)
    return fig


st.set_page_config(page_title="fbg-fp-demod pipeline", layout="wide")
st.title("fbg-fp-demod pipeline viewer")
st.write(
    "The method one spectrum at a time: raw spectrum, FFT with the pass "
    "band, filtered fringe with the Gaussian crest fit, and the resulting "
    "trajectory."
)

source = st.sidebar.radio("Data source", ["Synthetic scenario", "Interrogator file"])

if source == "Synthetic scenario":
    with st.sidebar.expander("Scenario", expanded=False):
        p_max = st.slider("Max pressure (bar)", 0.0, 3.0, 1.5, 0.1)
        t_max = st.slider("Max temperature rise (°C)", 0.0, 5.0, 2.0, 0.1)
        n_frames = st.slider("Frames", 20, 100, 60, 1)
        noise_db = st.slider("Noise (dB)", 0.0, 0.5, 0.2, 0.01)
        drift_db = st.slider("Baseline drift (dB)", 0.0, 1.0, 0.3, 0.05)
    opd_um = st.sidebar.slider("Cavity OPD (µm)", 50.0, 120.0, 87.0, 1.0)
    trim = st.sidebar.slider("Gaussian fit trim", 0.0, 0.4, 0.1, 0.01)
    wl, spectra_db, time_axis = synthetic_sequence(
        p_max, t_max, n_frames, noise_db, drift_db, opd_um * 1000.0
    )
    band = derived_band(opd_um * 1000.0, wl)
    reference_nm = SYNTH_REFERENCE_NM
    st.sidebar.caption(f"Pass band from OPD: {band[0]:.4f}-{band[1]:.4f} cycles/nm")
else:
    path = st.sidebar.text_input("Responses file path (stays on this machine)")
    channel = st.sidebar.number_input("Spectral channel (1-based, physical)", 1, 8, 2)
    reference_nm = st.sidebar.number_input("Tracking reference (nm)", value=1554.0)
    band = (
        st.sidebar.number_input("Band low (cycles/nm)", value=0.030, format="%.4f"),
        st.sidebar.number_input("Band high (cycles/nm)", value=0.042, format="%.4f"),
    )
    trim = st.sidebar.slider("Gaussian fit trim", 0.0, 0.4, 0.1, 0.01)
    max_spectra = st.sidebar.number_input(
        "Max spectra to load", 10, 10000, 300, 10,
        help="Large exports are read only up to this count.",
    )
    if not path:
        st.info("Enter the path of an ENLIGHT Responses export in the sidebar "
                "— e.g. one of your own recordings. It is read locally.")
        st.stop()
    try:
        wl, spectra_db, time_axis = load_export(path, int(channel), int(max_spectra))
    except (OSError, ValueError) as error:
        st.error(f"Could not read the file: {error}")
        st.stop()

try:
    corrected_nm, valley_nm, hop_frames = run_tracker(
        wl, spectra_db, band, reference_nm, trim
    )
except (ValueError, RuntimeError) as error:
    st.error(f"{error}\n\nThe tracker lost the fringe with these settings — "
             "adjust the band or the reference.")
    st.stop()

n_frames = spectra_db.shape[0]
frame = st.slider("Frame", 0, n_frames - 1, 0)

col_a, col_b, col_c = st.columns(3)
col_a.metric("Spectra", str(n_frames))
col_b.metric("Reading at this frame", f"{corrected_nm[frame]:.4f} nm")
col_c.metric("Fringe hops", str(len(hop_frames)))

try:
    st.pyplot(pipeline_figure(wl, spectra_db[frame], band, valley_nm[frame], trim))
except (ValueError, RuntimeError) as error:
    st.error(f"frame {frame}: {error}")
    st.stop()

shift_pm = (corrected_nm - corrected_nm[0]) * 1e3
if time_axis is None:
    st.pyplot(trajectory_figure(np.arange(n_frames), shift_pm, frame, "Frame"))
else:
    st.pyplot(trajectory_figure(time_axis, shift_pm, frame, "Time (h)"))
plt.close("all")
