"""Pipeline viewer for the fbg-fp-demod method.

The page reproduces the display the original MATLAB drew while it ran
(``FFT_FP_Aq_continua_V11_FFT_retangular.m``): on the left,
one spectrum through the method — normalized signal, its FFT with the
pass band and the in-band peak, and the band-filtered fringe with the
tracked crest picked out in red; on the right, the trajectory the
readings trace out and the FBG shifts. A frame slider steps through the
sequence.

The link between the two columns is the number itself: the reading
printed over the filtered spectrum is the same absolute nm plotted on
the trajectory, as MATLAB's ``total_wave_data(b) = pico_x`` was. The
voltage axis the MATLAB overlaid comes from a potentiostat export
(``Potentio_Data.Ewe_V``) that is not part of the interrogator data, so
it is left out rather than faked.

Two data sources: a synthetic scenario generated by ``fbgfp.synth`` (works
anywhere), or a local ENLIGHT ``Responses*.txt`` export read with
``fbgfp.io`` — the file is read on this machine and nothing leaves it.

Run with ``streamlit run app/main.py`` (requires ``pip install .[app]``).
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import streamlit as st

from fbgfp import fit, io, peaks, physics, synth, track

SYNTH_REFERENCE_NM = 1540.0
INTERNAL_FBG_NM = 1525.4
STATIC_FBG_NM = 1554.8
ORANGE = (1.0, 0.5, 0.0)  # the MATLAB's [1, 0.5, 0] window markers


def derived_band(opd_nm, wavelength_nm):
    """Pass band bracketing the fringe frequency f = OPD / wl^2."""
    f_max = opd_nm / wavelength_nm[0] ** 2
    f_min = opd_nm / wavelength_nm[-1] ** 2
    return 0.85 * f_min, 1.15 * f_max


@st.cache_data(max_entries=16)
def synthetic_sequence(p_max, t_max, n_frames, noise_db, drift_db, opd_nm):
    """A charge-like scenario mapped onto spectra through the calibration."""
    frames = np.arange(n_frames)
    pressure = p_max * (1.0 - np.exp(-frames / 15.0))
    temperature = t_max * np.sin(np.pi * frames / n_frames)
    delta_fpi = (
        physics.FPI_PRESSURE_NM_PER_BAR * pressure
        + physics.FPI_TEMPERATURE_NM_PER_C * temperature
    )
    crest0 = opd_nm / np.rint(opd_nm / SYNTH_REFERENCE_NM - 0.5)
    centers = np.column_stack(
        [
            INTERNAL_FBG_NM + physics.FBG_TEMPERATURE_NM_PER_C * temperature,
            np.full(n_frames, STATIC_FBG_NM),
        ]
    )
    wl = synth.wavelength_axis()
    seq = synth.simulate_sequence(
        wl,
        opd_nm=opd_nm * (1.0 + delta_fpi / crest0),
        fbg_centers_nm=centers,
        noise_db=noise_db,
        drift_amplitude_db=drift_db,
        seed=0,
    )
    return wl, seq.spectra_db, None  # no timestamps for synthetic frames


@st.cache_data(max_entries=4)
def load_export(path, channel, max_spectra):
    loaded = io.read_responses(path, channel=channel, max_spectra=max_spectra)
    hours = [
        (t - loaded.timestamps[0]).total_seconds() / 3600.0
        for t in loaded.timestamps
    ]
    return loaded.wavelength_nm, loaded.spectra_db, np.array(hours)


@st.cache_data(max_entries=16)
def run_tracker(wavelength_nm, spectra_db, band, reference_nm, trim):
    result = track.track_fp(spectra_db, wavelength_nm, band, reference_nm, trim=trim)
    return (
        result.crest_nm,
        result.corrected_nm,
        result.valley_nm,
        result.hop_frames,
        result.hop_fringes,
    )


@st.cache_data(max_entries=16)
def run_fbg_tracker(wavelength_nm, spectra_db, centers_nm, window_nm):
    return track.track_fbg(
        spectra_db, wavelength_nm, centers_nm, window_nm=window_nm
    )


def pipeline_figure(wl, spectrum_db, band, tracked_valley_nm, trim,
                    *, frame=None, n_frames=None):
    """The three per-spectrum panels, and the reading they print.

    Returns ``(figure, reading_nm)``. The reading is the raw fitted crest
    — the MATLAB's ``pico_x``, the quantity the trajectory plots.
    """
    step_nm = wl[1] - wl[0]
    normalized = peaks.linearize(spectrum_db)
    filtered = peaks.fft_bandpass(normalized, step_nm, band)
    valleys = peaks.find_valleys(wl, filtered)
    left, right = peaks.nearest_valley_pair(valleys, tracked_valley_nm)
    crest = fit.fit_fringe_crest(wl, filtered, left, right, trim=trim)

    fig, axes = plt.subplots(3, 1, figsize=(8.5, 9), constrained_layout=True)

    axes[0].plot(wl, normalized, "k", lw=0.4)
    axes[0].set_title("Normalized signal")
    axes[0].set_xlabel("Wavelength (nm)")
    # linearize returns min-max normalized linear power, not dB: the MATLAB
    # kept its dB label here after normalizing, which this does not copy.
    axes[0].set_ylabel("Normalized power (a.u.)")

    freqs = np.fft.rfftfreq(normalized.size, d=step_nm)
    amplitude = np.abs(np.fft.rfft(normalized - normalized.mean()))
    amplitude /= amplitude.max()
    in_band = (freqs >= band[0]) & (freqs <= band[1])
    peak = np.flatnonzero(in_band)[np.argmax(amplitude[in_band])]
    show = freqs <= max(3.0 * band[1], 0.1)
    axes[1].plot(freqs[show], amplitude[show], "k", lw=0.8)
    axes[1].axvspan(band[0], band[1], color="tab:red", alpha=0.25,
                    label=f"pass band {band[0]:.4f}-{band[1]:.4f}")
    axes[1].plot(freqs[peak], amplitude[peak], "*r", ms=10,
                 label=f"in-band peak {freqs[peak]:.4f} cycles/nm")
    axes[1].set_ylim(0.0, amplitude[peak] * 1.5)
    axes[1].set_title("FFT of the normalized spectrum (spatial frequency)")
    axes[1].set_xlabel("Frequency (cycles/nm)")
    axes[1].set_ylabel("Normalized amplitude")
    axes[1].legend(fontsize=8)

    # The tracked fringe in red against the black spectrum, and the trim
    # window in orange, exactly the marks the MATLAB used to make which
    # fringe is being followed unmistakable at a glance.
    span = right - left
    low, high = left + trim * span, right - trim * span
    window = (wl >= low) & (wl <= high)
    axes[2].plot(wl, filtered, "k", lw=0.5)
    axes[2].plot([left, right], filtered[np.searchsorted(wl, [left, right])],
                 "*r", ms=10, label="bracketing valleys")
    axes[2].plot(wl[window],
                 fit.gaussian(wl[window], crest.amplitude, crest.center,
                              crest.sigma, crest.offset),
                 "r", lw=1.5, label="Gaussian crest fit")
    axes[2].plot(crest.center,
                 fit.gaussian(crest.center, crest.amplitude, crest.center,
                              crest.sigma, crest.offset),
                 "r*", ms=12, label=f"reading {crest.center:.5f} nm")
    for edge in (low, high):
        axes[2].axvline(edge, color=ORANGE, lw=1.0)
    counted = "" if frame is None else f"file nro: {frame + 1}/{n_frames}, "
    axes[2].set_title(
        f"Band-filtered signal, {counted}Actual reading: {crest.center:.5f}"
    )
    axes[2].set_xlabel("Wavelength (nm)")
    axes[2].set_ylabel("Filtered amplitude (a.u.)")
    axes[2].legend(loc="lower left", fontsize=8)
    return fig, crest.center


def trajectory_figure(x, crest_nm, corrected_nm, hop_fringes, frame, xlabel):
    """The readings over time, in the absolute nm the spectrum panel prints.

    When the tracker has unwrapped a fringe hop the corrected series is
    drawn alongside: the raw reading is what the spectrum panel shows,
    the corrected one is what differences should be taken on.

    ``hop_fringes`` is signed by where the tracked fringe went along the
    wavelength axis, which is not what the MATLAB's "Jumps up/down"
    counted — those counted the peak leaving the top or bottom of the
    scan, and were dead code that always printed zero. The labels here
    say which they are.
    """
    ups = sum(1 for n in hop_fringes if n > 0)
    downs = sum(1 for n in hop_fringes if n < 0)
    fig, ax = plt.subplots(figsize=(8.5, 4.2), constrained_layout=True)
    ax.plot(x, crest_nm, "k-", lw=0.9, label="reading (raw crest)")
    if hop_fringes:
        ax.plot(x, corrected_nm, "-", color="tab:blue", lw=0.9,
                label="unwrapped (good to ~0.6 nm per hop)")
    ax.plot(x[frame], crest_nm[frame], "o", ms=9, mfc="none", mec="r", mew=1.6,
            label=f"this frame: {crest_nm[frame]:.5f} nm")
    ax.set_title(
        f"Peak maximum vs time (Fringe hops: {ups} up the axis . "
        f"{downs} down the axis, Peak Record = {crest_nm[frame]:.3f})"
    )
    ax.set_xlabel(xlabel)
    ax.set_ylabel("CrestPosition(nm)")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    return fig


def fbg_figure(x, fbg_nm, labels, xlabel):
    """FBG Bragg shifts, each against its own first reading."""
    palette = ("r", "b", "g", "m", "c", "y")
    fig, ax = plt.subplots(figsize=(8.5, 4.2), constrained_layout=True)
    for column, label in enumerate(labels):
        ax.plot(x, fbg_nm[:, column] - fbg_nm[0, column],
                palette[column % len(palette)], lw=0.9, label=label)
    ax.set_title("FBG shift vs time")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("BraggWave(nm)")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    return fig


st.set_page_config(page_title="fbg-fp-demod pipeline", layout="wide")
st.title("fbg-fp-demod pipeline viewer")
st.write(
    "The method one spectrum at a time, laid out as the original MATLAB "
    "drew it: normalized signal, FFT with the pass band, the filtered "
    "fringe with the tracked crest in red — and, on the right, the same "
    "readings over time, in the same nanometres."
)

source = st.sidebar.radio("Data source", ["Synthetic scenario", "Interrogator file"])

if source == "Synthetic scenario":
    with st.sidebar.expander("Scenario", expanded=False):
        p_max = st.slider("Max pressure (bar)", 0.0, 3.0, 1.5, 0.1)
        t_max = st.slider("Max temperature rise (°C)", 0.0, 5.0, 2.0, 0.1)
        n_frames = st.slider("Frames", 20, 100, 60, 1)
        noise_db = st.slider("Noise (dB)", 0.0, 0.5, 0.2, 0.01)
        drift_db = st.slider("Baseline drift (dB)", 0.0, 1.0, 0.3, 0.05)
    opd_um = st.sidebar.slider("Cavity OPD (µm)", 50.0, 120.0, 87.0, 1.0)
    trim = st.sidebar.slider("Gaussian fit trim", 0.0, 0.4, 0.1, 0.01)
    wl, spectra_db, time_axis = synthetic_sequence(
        p_max, t_max, n_frames, noise_db, drift_db, opd_um * 1000.0
    )
    band = derived_band(opd_um * 1000.0, wl)
    reference_nm = SYNTH_REFERENCE_NM
    fbg_centers = (INTERNAL_FBG_NM, STATIC_FBG_NM)
    fbg_labels = ("FBG Interna", "FBG Externa")
    st.sidebar.caption(f"Pass band from OPD: {band[0]:.4f}-{band[1]:.4f} cycles/nm")
else:
    path = st.sidebar.text_input("Responses file path (stays on this machine)")
    channel = st.sidebar.number_input("Spectral channel (1-based, physical)", 1, 8, 2)
    reference_nm = st.sidebar.number_input("Tracking reference (nm)", value=1554.0)
    band = (
        st.sidebar.number_input("Band low (cycles/nm)", value=0.030, format="%.4f"),
        st.sidebar.number_input("Band high (cycles/nm)", value=0.042, format="%.4f"),
    )
    trim = st.sidebar.slider("Gaussian fit trim", 0.0, 0.4, 0.1, 0.01)
    max_spectra = st.sidebar.number_input(
        "Max spectra to load", 10, 10000, 300, 10,
        help="Large exports are read only up to this count.",
    )
    fbg_text = st.sidebar.text_input(
        "FBG centres (nm, comma separated)",
        help="Leave empty to skip the FBG panel. The interrogator's own "
             "Peaks export is the measurement of record for these.",
    )
    fbg_centers, fbg_labels = (), ()
    if fbg_text.strip():
        try:
            fbg_centers = tuple(float(v) for v in fbg_text.split(","))
        except ValueError:
            st.sidebar.error("FBG centres must be numbers separated by commas.")
        fbg_labels = tuple(f"FBG {v:.1f} nm" for v in fbg_centers)
    if not path:
        st.info("Enter the path of an ENLIGHT Responses export in the sidebar "
                "— e.g. one of your own recordings. It is read locally.")
        st.stop()
    try:
        wl, spectra_db, time_axis = load_export(path, int(channel), int(max_spectra))
    except (OSError, ValueError) as error:
        st.error(f"Could not read the file: {error}")
        st.stop()

try:
    crest_nm, corrected_nm, valley_nm, hop_frames, hop_fringes = run_tracker(
        wl, spectra_db, band, reference_nm, trim
    )
except (ValueError, RuntimeError) as error:
    st.error(f"{error}\n\nThe tracker lost the fringe with these settings — "
             "adjust the band or the reference.")
    st.stop()

n_frames = spectra_db.shape[0]
frame = st.slider("Frame", 0, n_frames - 1, 0)
x_axis = np.arange(n_frames) if time_axis is None else time_axis
xlabel = "Frame" if time_axis is None else "Elapsed time (h)"

col_a, col_b, col_c = st.columns(3)
col_a.metric("Spectra", str(n_frames))
col_b.metric("Reading at this frame", f"{crest_nm[frame]:.4f} nm")
col_c.metric("Fringe hops", str(len(hop_frames)))

if frame in hop_frames:
    st.warning(
        f"Frame {frame} is a fringe hop: the tracker moved to a neighbouring "
        f"fringe, so the raw reading steps by about one fringe here. The "
        f"unwrapped series absorbs that step, but only to within the valley "
        f"spacing measured at the spectrum edge — around 0.6 nm per hop, far "
        f"coarser than the picometre readings away from a hop."
    )

left_col, right_col = st.columns(2)
with left_col:
    try:
        figure, _ = pipeline_figure(
            wl, spectra_db[frame], band, valley_nm[frame], trim,
            frame=frame, n_frames=n_frames,
        )
        st.pyplot(figure)
    except (ValueError, RuntimeError) as error:
        st.error(f"frame {frame}: {error}")
        st.stop()

with right_col:
    st.pyplot(
        trajectory_figure(x_axis, crest_nm, corrected_nm, hop_fringes, frame, xlabel)
    )
    if fbg_centers:
        try:
            fbg_nm = run_fbg_tracker(wl, spectra_db, fbg_centers, 1.0)
            st.pyplot(fbg_figure(x_axis, fbg_nm, fbg_labels, xlabel))
        except ValueError as error:
            st.warning(f"FBG tracking stopped: {error}")

plt.close("all")
