"""Interactive playground for the fbg-fp-demod pipeline.

Streamlit front-end over the same public API the demo script uses:
a sidebar scenario drives a synthetic Fabry-Perot + FBG fibre, the
demodulator recovers pressure and temperature from the spectra alone,
and the page compares truth against recovery. Everything on screen is
generated by ``fbgfp.synth``; no measured data is involved.

Run with ``streamlit run app/main.py`` (requires ``pip install .[app]``).
"""

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import streamlit as st

from fbgfp import fit, peaks, physics, synth, track

WL_START_NM, WL_STEP_NM, WL_POINTS = 1460.0, 0.008, 20000  # interrogator grid
REFERENCE_NM = 1540.0  # mid-axis tracking reference
INTERNAL_FBG_NM = 1525.4  # temperature sensor used for demodulation
STATIC_FBG_NM = 1554.8  # multiplexing companion, present but not tracked


def derived_band(opd_nm):
    """Pass band bracketing the fringe's local frequency f = OPD / wl^2.

    The frequency falls with wavelength, so the axis ends give its full
    range; the 0.85/1.15 margins absorb the OPD excursion of the scenario.
    """
    wl_end = WL_START_NM + WL_STEP_NM * (WL_POINTS - 1)
    f_max, f_min = opd_nm / WL_START_NM**2, opd_nm / wl_end**2
    return 0.85 * f_min, 1.15 * f_max


@st.cache_data(max_entries=64)
def run_pipeline(p_max, t_max, n_frames, noise_db, drift_db, opd_nm, trim, band):
    """Generate, demodulate, and package plain arrays for display.

    One cached unit keyed by every control: moving any slider recomputes,
    moving none redraws instantly.
    """
    frames = np.arange(n_frames)
    pressure_true = p_max * (1.0 - np.exp(-frames / 15.0))
    temperature_true = t_max * np.sin(np.pi * frames / n_frames)

    # The sensitivities map the scenario onto spectral trajectories...
    delta_fpi = (
        physics.FPI_PRESSURE_NM_PER_BAR * pressure_true
        + physics.FPI_TEMPERATURE_NM_PER_C * temperature_true
    )
    delta_fbg = physics.FBG_TEMPERATURE_NM_PER_C * temperature_true

    # ...scaled through the crest the tracker actually follows: the one
    # bracketed by the valley nearest the reference and its right
    # neighbour, i.e. fringe order floor(opd/reference).
    crest0_nm = opd_nm / np.rint(opd_nm / REFERENCE_NM - 0.5)
    centers = np.column_stack(
        [INTERNAL_FBG_NM + delta_fbg, np.full(n_frames, STATIC_FBG_NM)]
    )
    wl = synth.wavelength_axis(WL_START_NM, WL_STEP_NM, WL_POINTS)
    seq = synth.simulate_sequence(
        wl,
        opd_nm=opd_nm * (1.0 + delta_fpi / crest0_nm),
        fbg_centers_nm=centers,
        noise_db=noise_db,
        drift_amplitude_db=drift_db,
        seed=0,
    )

    fp = track.track_fp(seq.spectra_db, wl, band, REFERENCE_NM, trim=trim)
    fbg = track.track_fbg(seq.spectra_db, wl, [INTERNAL_FBG_NM])
    pressure, temperature = physics.separate_pressure_temperature(
        fbg[:, 0] - fbg[0, 0], fp.corrected_nm - fp.corrected_nm[0]
    )

    # Frame 0 demodulated step by step, for the method figure.
    filtered = peaks.fft_bandpass(peaks.linearize(seq.spectra_db[0]), WL_STEP_NM, band)
    valleys = peaks.find_valleys(wl, filtered)
    left, right = peaks.nearest_valley_pair(valleys, REFERENCE_NM)
    crest = fit.fit_fringe_crest(wl, filtered, left, right, trim=trim)

    return {
        "wavelength_nm": wl,
        "spectrum0_db": seq.spectra_db[0],
        "filtered0": filtered,
        "crest_params": (crest.amplitude, crest.center, crest.sigma, crest.offset),
        "crest_window": (left, right),
        "pressure_true": pressure_true,
        "temperature_true": temperature_true,
        "pressure": pressure,
        "temperature": temperature,
        "n_hops": len(fp.hop_frames),
    }


def sidebar_controls():
    """All user inputs, returned as the cache key of ``run_pipeline``."""
    with st.sidebar:
        st.header("Scenario")
        p_max = st.slider("Max pressure (bar)", 0.0, 3.0, 1.5, 0.1)
        t_max = st.slider("Max temperature rise (°C)", 0.0, 5.0, 2.0, 0.1)
        n_frames = st.slider("Frames", 20, 100, 60, 1)
        noise_db = st.slider("Noise (dB)", 0.0, 0.5, 0.2, 0.01)
        drift_db = st.slider("Baseline drift (dB)", 0.0, 1.0, 0.3, 0.05)

        st.header("Sensor & method")
        opd_um = st.slider("Cavity OPD (µm)", 50.0, 120.0, 87.0, 1.0)
        trim = st.slider("Gaussian fit trim", 0.0, 0.4, 0.1, 0.01)

        low, high = derived_band(opd_um * 1000.0)
        st.caption(f"FFT pass band, derived from OPD: {low:.4f}-{high:.4f} cycles/nm")
        with st.expander("Advanced"):
            override = st.checkbox("Override band")
            # Stable keys: without them the inputs are re-created (and thus
            # reset to the derived values) every time the OPD slider moves.
            band_low = st.number_input(
                "Band low (cycles/nm)", value=float(low), step=0.001,
                format="%.4f", key="band_low",
            )
            band_high = st.number_input(
                "Band high (cycles/nm)", value=float(high), step=0.001,
                format="%.4f", key="band_high",
            )
        band = (band_low, band_high) if override else (low, high)

    return dict(
        p_max=p_max,
        t_max=t_max,
        n_frames=n_frames,
        noise_db=noise_db,
        drift_db=drift_db,
        opd_nm=opd_um * 1000.0,
        trim=trim,
        band=band,
    )


def method_figure(r):
    """Frame 0: raw multiplexed spectrum, then the demodulator's view of it."""
    wl = r["wavelength_nm"]
    fig, (top, bottom) = plt.subplots(2, 1, figsize=(10, 6), constrained_layout=True)
    top.plot(wl, r["spectrum0_db"], lw=0.4)
    top.set_title("Frame 0: synthetic multiplexed spectrum (FP fringe + 2 FBG peaks)")
    top.set_ylabel("Power (dB)")

    bottom.plot(wl, r["filtered0"], lw=0.5, label="band-passed fringe")
    left, right = r["crest_window"]
    window = (wl >= left) & (wl <= right)
    center = r["crest_params"][1]
    bottom.plot(
        wl[window],
        fit.gaussian(wl[window], *r["crest_params"]),
        "--",
        lw=1.5,
        label=f"Gaussian crest fit: {center:.3f} nm",
    )
    bottom.set_title("FFT band-pass + Gaussian crest fit")
    bottom.set_xlabel("Wavelength (nm)")
    bottom.set_ylabel("Filtered amplitude")
    bottom.legend(loc="lower left", fontsize=8)
    return fig


def recovery_figure(r):
    """Truth (line) against demodulated (dots), pressure and temperature."""
    fig, (left, right) = plt.subplots(1, 2, figsize=(10, 4), constrained_layout=True)
    for ax, name, unit in ((left, "pressure", "bar"), (right, "temperature", "°C")):
        ax.plot(r[f"{name}_true"], "-", label="true")
        ax.plot(r[name], ".", ms=4, label="recovered from spectra")
        ax.set_title(f"{name.capitalize()}: truth vs demodulated")
        ax.set_xlabel("Frame")
        ax.set_ylabel(f"{name.capitalize()} change ({unit})")
        ax.legend()
    return fig


st.set_page_config(page_title="fbg-fp-demod playground", layout="wide")
st.title("fbg-fp-demod playground")
st.write(
    "Synthetic spectra in, pressure and temperature out: pick a scenario in "
    "the sidebar and watch the demodulator recover it. No measured data — "
    "every spectrum is generated by this repository's own code."
)

params = sidebar_controls()
try:
    result = run_pipeline(**params)
except (ValueError, RuntimeError) as error:
    st.error(
        f"{error}\n\nThe tracker lost the fringe with these settings — "
        "widen the band or reduce the excursion."
    )
    st.stop()

rms_p = float(np.sqrt(np.mean((result["pressure"] - result["pressure_true"]) ** 2)))
rms_t = float(np.sqrt(np.mean((result["temperature"] - result["temperature_true"]) ** 2)))
col_p, col_t, col_h = st.columns(3)
col_p.metric("RMS pressure error", f"{rms_p:.3f} bar")
col_t.metric("RMS temperature error", f"{rms_t:.2f} °C")
col_h.metric(
    "Fringe hops", str(result["n_hops"]),
    help="Expected 0: the reachable excursions stay far below one fringe.",
)

for figure in (method_figure(result), recovery_figure(result)):
    st.pyplot(figure)
    plt.close(figure)
